### ISSUE TITLE
Spikes in gas readings?

### ISSUE THREAD

**Issue by jljanisse** [XiloXL/Powerbaas#8]
I received the ESP32 and breakout on the weekend and it works better than expected.  The included examples are more than I was expecting.  I have made some changes to send the readings to the Arduino IoT cloud dashboard.  The only thing is that I observe some strange spikes on the gas reading. 

The reading jumps by 3 orders of magnitude from 5730595 to 4,94567000.  Is this something that has been observed before?  I dont mind adding a line of code to check for and skip these spiked but just curious if my P1 meter is behaving badly.

James
![Capture](https://user-images.githubusercontent.com/63845214/205886628-c2adc7f2-e61f-4a48-b226-49eecf36838e.JPG)

**Comment by XiloXL** [comment]
Hi @jljanisse, 

It could be due to an overflow while parsing to a float.
I just released a bug fix in a new release: https://github.com/XiloXL/Powerbaas/releases/tag/v1.3.6
This release should be available in Arduino in a couple of hours.
Can you let us know if this fixes your issue?

Kind regards,

Gerard Oudenampsen 
Powerbaas.nl
